CREATE TABLE IF NOT EXISTS cocktails_details(
    drink_id INTEGER,
    drink_name TEXT,
    drink_alternate_name TEXT,
    drink_tags TEXT,
    drink_category TEXT,
    drink_iba TEXT,
    is_alcoholic TEXT,
    drink_glass TEXT,
    instructions TEXT,
    instructions_de TEXT
);

-- CREATE TABLE IF NOT EXISTS cocktails_details(
--     idDrink INTEGER,
--     strDrink TEXT,
--     strDrinkAlternate TEXT,
--     strTags TEXT,
--     strCategory TEXT,
--     strIBA TEXT,
--     strAlcoholic TEXT,
--     strGlass TEXT,
--     strInstructions TEXT,
--     strInstructionsDE TEXT,
--     strIngredient1 TEXT,
--     strIngredient2 TEXT,
--     strIngredient3 TEXT,
--     strIngredient4 TEXT,
--     strIngredient5 TEXT,
--     strIngredient6 TEXT,
--     strIngredient7 TEXT,
--     strIngredient8 TEXT,
--     strIngredient9 TEXT,
--     strIngredient10 TEXT,
--     strIngredient11 TEXT,
--     strIngredient12 TEXT,
--     strIngredient13 TEXT,
--     strIngredient14 TEXT,
--     strIngredient15 TEXT,
--     strMeasure1 TEXT,
--     strMeasure2 TEXT,
--     strMeasure3 TEXT,
--     strMeasure4 TEXT, 
--     strMeasure5 TEXT,
--     strMeasure6 TEXT,
--     strMeasure7 TEXT,
--     strMeasure8 TEXT,
--     strMeasure9 TEXT,
--     strMeasure10 TEXT, 
--     strMeasure11 TEXT,
--     strMeasure12 TEXT, 
--     strMeasure13 TEXT,
--     strMeasure14 TEXT,
--     strMeasure15 TEXT     
-- );